### ISSUE TITLE
Arras duplicate text on header 

### ISSUE THREAD

**Issue by Clizia63** [iCaspar/arras#58]
I Caspar.
I’m testing Arras 1.7 for my under construction site. I’m using All-in-One Event Calendar plugin and in Event Page occurs a duplicate text on header. This error occurs in version 1.5 too. This error occurs in version 1.6 too, but to a lesser extent. This error doesn’t occurs in version 3.
I post you a screen shot of error.
Thank you
![duplicate on event page](https://user-images.githubusercontent.com/34421809/33807432-4f17ed8a-ddd7-11e7-9a2b-8fb24b191c7a.jpg)

**Comment by iCaspar** [comment]
Fixed. (51718c3) Released as v1.7.1. Please check new download on arrastheme.net

Thanks again, @Clizia63 for reporting this.

**Comment by Clizia63** [comment]
Thanks for your work but the bug is partially solved.  The rows HTML into the header
 were repeated twice before fix. Now, after fix, the rows HTML into the header  are produced once.

![immagine](https://user-images.githubusercontent.com/34421809/33856924-ff698e44-dec9-11e7-98af-3d9dc14f3bef.png)

**Comment by iCaspar** [comment]
I am unable to reproduce this from here. Is it possible for me to see that page in a browser? Also, do you have any plugins running (such as an SEO plugin) that may be inserting into the header?

**Comment by iCaspar** [comment]
Ok, I can see it now. I'll get a new patch started. Until then, you can confirm the fix by commenting out line 77 in `functions.php`. It's the line that reads:

`add_action( 'wp_head', 'arras_add_facebook_share_meta' );`

Let me know if that resolves. Thanks again for your help.

**Comment by Clizia63** [comment]
Well done, now it is ok. 
Thanks a lot to you.
